PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

SELECT ?q ?answer WHERE {
  ?x schema:text ?answer;
     schema:headline ?q;
     schema:upvoteCount ?score;
     schema:ItemList "trump"^^<http://schema.org/itemListElement>.
}
ORDER BY DESC(?score) LIMIT 6
